phosphor-objmgr: srcrev bump 21c6059531..e82b05840b
Patrick Williams (2):
      exception: switch from org.freedesktop to openbmc
      mapper-wait: handle switch to openbmc exceptions

Change-Id: I969c7baf6f649aebfbb2a5bf0d7803f617044858
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>