Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1:
> > > 
> > > > Patch Set 1:
> > > > 
> > > > > Patch Set 1:
> > > > > 
> > > > > > Patch Set 1:
> > > > > > 
> > > > > > > Patch Set 1:
> > > > > > > 
> > > > > > > > Patch Set 1: Code-Review-1
> > > > > > > > 
> > > > > > > > (1 comment)
> > > > > > > > 
> > > > > > > > > Patch Set 1:
> > > > > > > > > 
> > > > > > > > > Lei, does this match what you're using for your 64MB machine?
> > > > > > > > 
> > > > > > > > Nope, what we were doing is to:
> > > > > > > > * upstream the 64MiB layout dts to https://github.com/openbmc/linux/blob/dev-5.8/arch/arm/boot/dts/openbmc-flash-layout-64.dtsi
> > > > > > > > * Define the machine config in https://github.com/openbmc/meta-bytedance/blob/master/meta-g220a/conf/machine/g220a.conf#L6-L9
> > > > > > > > 
> > > > > > > > But it's a good idea to define the "default 64MiB layout" here, which needs to be synced with openbmc-flash-layout-64.dtsi.
> > > > > > > 
> > > > > > > Be noted that it's OK to update the openbmc-flash-layout-64.dtsi if necessary, and we will keep sync with the upstream change in our system.
> > > > > > 
> > > > > > The layout I created here according to https://github.com/openbmc/linux/blob/dev-5.8/arch/arm/boot/dts/aspeed-ast2600-evb.dts#L125-L154 . 
> > > > > > 
> > > > > > I'll update this patch set and also send a patch for aspeed-ast2600-evb.dts leveraging openbmc-flash-layout-64.dtsi. 
> > > > > > 
> > > > > > Thanks for the review.
> > > > > 
> > > > > @Lei Yu,
> > > > > 
> > > > > It turns out 384KB (defined in openbmc-flash-layout-64.dtsi) is not enough for AST2600 u-boot. Is it possible to move 512KB from rofs/rwfs to u-boot partition? 
> > > > > 
> > > > > Thanks,
> > > > > Troy
> > > > 
> > > > Hi, Troy
> > > > 
> > > > > Is it possible to move 512KB from rofs/rwfs to u-boot partition? 
> > > > 
> > > > I tried, and add this to meta-bytedance/meta-g220a/conf/machine/g220a.conf
> > > > 
> > > > FLASH_KERNEL_OFFSET = "1024"
> > > > 
> > > > and I saw this:
> > > > 
> > > > Hit any key to stop autoboot:  0
> > > > Wrong Image Format for bootm command
> > > > ERROR: can't get kernel image!
> > > > ast#
> > > 
> > > I'm not sure why, I think what we want is a 64M layout that fits both ast-2500 and ast-2600
> > 
> > Hi John,
> > 
> > Have check the u-boot-env using the correct offset to kernel?
> > 
> > Thanks,
> > Troy Lee
> 
> emm, How can I check that ?
> 
> I tried to make the kernel offset to 1M  in dts and the KERNEL_FLASH_OFFSET variable  to 1M in g220a.conf.

emm, I see.

it works well after I set bootm=20008000 to 20100000.

https://github.com/openbmc/u-boot/blob/v2016.07-aspeed-openbmc/include/configs/ast-common.h#L111

For ast2500, the default offset is 20008000, should we submit a patch so that 2500/2600 can use the 64M layout

Patch-set: 1
Reviewer: Gerrit User 1000305 <1000305@adbd0a64-1f21-4d83-b585-671fe73cb6e4>