phosphor-misc: Create recipe
Create a recipe for the phosphor-misc repo with its current
configuration options.

Tested:
- Adding phosphor-misc to packagegroup-obmc-apps.bb does not
  cause any compilation errors, and does not install any files.
- Adding phosphor-misc to a packagegroup-obmc-apps.bbappend plus
  enabling the configurations from a phosphor-misc_%.bbappend
  installed the expected binaries and service files. Ex:
PACKAGECONFIG_append = " http_redirect"
PACKAGECONFIG_append = " first_boot_set_mac"
PACKAGECONFIG_append = " first_boot_set_hostname"
- Enabled the http_redirect configuration and verified that
  http://bmc got redirected to https://bmc to the GUI homepage.
  Masking out the IP addresses:
Jun 02 18:15:48 witherspoon-tacoma-YA30UF03400F systemd[1]: Started Redirect HTTP to HTTPS Per-connection (xxx.xxx.xxx.xxx:51413).
Jun 02 18:15:48 witherspoon-tacoma-YA30UF03400F systemd[1]: http-redirct@0-yyy.yyy.yyy.yyy:80-xxx.xxx.xxx.xxx:51413.service: Succeeded.

Change-Id: I16a06b5f6adedd41ce078d76b3bbe96d69f9413b
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>