phosphor-objmgr: srcrev bump 21c6059531..3735ea2ee5
Patrick Williams (1):
      exception: switch from org.freedesktop to openbmc

Change-Id: I995baf87f81721cab45f8773378623b6e5b4ec95
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>