switchtec: microsemi command line debug tool
Used to interact with microsemi switchtec devices. This tool could be
useful for teams bringing up new microsemi devices via the BMC.

This currently does not compile with the following errors:
ERROR: switchtec-2.4-r0 do_compile: oe_runmake failed
ERROR: switchtec-2.4-r0 do_compile: Execution of '/home/andrewg/Code/openbmc/build/witherspoon/tmp/work/arm1176jzs-openbmc-linux-gnueabi/switchtec/2.4-r0/temp/run.do_compile.1519536' failed with exit code 1:
make: ./VERSION-GEN: Command not found
make: *** No rule to make target 'examples/temp', needed by 'compile'.  Stop.
make: *** Waiting for unfinished jobs....

Also, need to look into upstreaming this to meta-openembedded since it
could be useful for other projects.

Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
Change-Id: I835bd2848841a4c8d3efc9dfad64cd7f7fc32a47